version: "3"
services:
  selenium:
    image: seleniarm/standalone-chromium:4.1.4-20220429
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - kot
  app:
    build:
      context: .
      dockerfile: docker/kot/Dockerfile
    volumes:
      - .:/app
      - $HOME/.kot/config.yaml:/kot/config.yaml
    environment:
      SELENIUM_URL: 'http://selenium:4444/wd/hub'
    command: kot scrape --console --browser-kind remote
    tty: true
    depends_on:
      - selenium
    networks:
      - kot

networks:
  kot: null
