name: Dockerfile linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Pull hadolint image
      run: docker pull hadolint/hadolint
    - name: Run hadolint
      run: docker run --rm -i hadolint/hadolint < Dockerfile
