name: Python application

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export -f requirements.txt > requirements.txt
        pip freeze | xargs pip uninstall -y
        pip install --user -r requirements.txt
    - name: Check type with mypy
      run: |
        pip install mypy
        mypy py --ignore-missing-imports
    - name: Test with pytest
      run: |
        pip install pytest
        pytest py/tests
